name: simple java application 

on: 
  push:
     branches: [ master ]

  pull_request:
     branches: [ main, 'feature/*' ]
     
  workflow_dispatch: 
     

jobs:
   my-first-job:
       runs-on: ubuntu-latest
       steps:
       - name: simple step 
         run: echo "This is sample java application"

       - name: checkout the repo 
         uses: actions/checkout@v6.0.1

       - name: Set up Java 21
         uses: actions/setup-java@v4
         with:
           distribution: temurin
           java-version: 21  

       - name: check java is installed or not 
         run: java -version 

       - name: mvn
         run: mvn clean package 
          
      
